### PR TITLE
Review

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
Thanks for this module! I've a look at the code and have some change suggestions. In the commit messages I've wrote more details.

In addition to a few detail optimizations, this will solve #2 and #3.

There are no functional changes.

### CODE REVIEW

**Review by retroflex — COMMENTED** [review]
Very nice work! Just one question: why commit package-lock.json if it is in the ignore list? I thought the common practise for MM was to not commit that file.

**Comment by KristjanESPERANTO** [comment]
Oh, I missed that. Thanks. I've just removed it :slightly_smiling_face:

**Comment by KristjanESPERANTO** [comment]
With the changes, your module now looks nice on [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) :smiley:.

**Comment by retroflex** [comment]
Niiice! I especially like the hints for devs. Btw, any reason why MMM-TextPerWeek doesn't show a license?

**Comment by KristjanESPERANTO** [comment]
Thanks for the positive feedback! :smiley: 

Yes, the licence and keywords are ridden from the package.json and in MMM-TextPerWeek is none. Would be nice if you could add it.

**Comment by KristjanESPERANTO** [comment]
And in order for screenshots to be included, they must be placed directly in the repository (which directory doesn't matter). It would be super cool if you could do that for all your modules 🙏

**Comment by retroflex** [comment]
Thanks again för your help and good work! I'll see if I get some time to look at it...

**Pull request merged**
